[versions]
agp = "8.6.0"
kotlin = "1.9.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.0"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
coroutines = "1.5.2"
hilt = "2.46.1"
hiltNavigationCompose = "1.2.0"
okhttp = "4.11.0"
retrofit = "2.9.0"
composeViewModel = "2.8.7"
composeNavigation = "2.8.3"
jsonSerialization = "1.6.0"
kotlinSerializationConverter = "1.0.0"
material = "1.7.4"
appcompat = "1.7.0"
paging3 = "3.3.2"
composeFoundation = "1.7.5"
coil = "2.7.0"
zxingAndroid = "4.1.0"
zxingCore = "3.5.3"
moshi = "1.15.2"
vicoChart = "1.12.0"
lottie = "6.3.0"
mockk = "1.13.5"
truth = "1.1.3"
coroutines-test = "1.5.2"
mockwebserver = "4.11.0"
junitJupiter = "5.9.3"
uiTestJunit4Android = "1.8.3"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

androidx-navigation-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-compose-material-meterial = { group = "androidx.compose.material", name = "material", version.ref = "material" }

json-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jsonSerialization" }
kotlin-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinSerializationConverter" }

viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging3" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging3" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging3" }

compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeFoundation" }

# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Zxing
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingAndroid" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }

#Moshi
squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
squareup-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

#Vico
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vicoChart" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vicoChart" }
vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vicoChart" }
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vicoChart" }

#Lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

#Unit Test
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

#Integration Test
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }

dagger-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Junit5
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }

[bundles]
coroutines = ["coroutines-android", "coroutines-core"]
okhttp = ["squareup-okhttp3-okhttp", "squareup-okhttp3-logging-interceptor"]
retrofit = ["squareup-retrofit2-retrofit"]
serialization = ["json-serialization", "kotlin-serialization-converter"]
paging = ["paging-runtime", "paging-compose"]
vico = ["vico-compose", "vico-compose-m3", "vico-core", "vico-views"]
zxing = ["zxing-core", "zxing-android-embedded"]
moshi = ["squareup-moshi", "squareup-moshi-kotlin"]
junit5 = [
    "junit-jupiter-api",
    "junit-jupiter-params"
]

android-test = [
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-ui-test-junit4",
    "dagger-hilt-android-testing"
]

test = [
    "junit",
    "androidx-junit",
    "coroutines-test",
    "mockk",
    "mockwebserver",
    "truth",
    "dagger-hilt-android-testing"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

